services:

  db:
    image: postgres:16.0
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_PORT=5432

  odoo:
    image: local-odoo
    depends_on:
      - db
    ports:
      - 80:8069
